### PR TITLE
UI of Number Guessing Game Website is improved

### LINKED ISSUE #849: [Feature Request]: Improve the UI of Number Guessing Game Website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to improve the UI so that it becomes more attractive

### Use Case

This change will improve its user experience with this page

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Sanglap-Halder**
# Title and Issue number 

Title : UI of Number Guessing Game Website is improved

Issue No. : 849

Code Stack : 

Close #849

# Video (mandatory)

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

### **Before:** 
Screenshot (175)

### **After:** 
guessthenum

***Are you contributing under any Open-source programme?***

- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor

### CODE REVIEW

**Review by apu52 — APPROVED** [review]
@Sanglap-Halder well made changes

**Review by apu52 — CHANGES_REQUESTED** [review]
@Sanglap-Halder why this commit present in this PR , as it is unnecessary for this PR , please try to discard this from this pR , otherwise I can't be able to merge this PR

**Comment by Sanglap-Halder** [comment]
I don't understand what you are saying.
About which commit are you telling?
Actually I am a beginner in open source contributions. Maybe that's why I have made mistakes.

**Comment by apu52** [comment]
> I don't understand what you are saying. About which commit are you telling? Actually I am a beginner in open source contributions. Maybe that's why I have made mistakes.

image

This "Blog Website" commit as it is already been part of another pR which is already merged . So this Commit is unnecessary in this PR . I would like to suggest you that whenever u try to submit new PR make different branches according to that PR (in your forked repo)& then submit your PR.

**Comment by apu52** [comment]
> I don't understand what you are saying. About which commit are you telling? Actually I am a beginner in open source contributions. Maybe that's why I have made mistakes.

if u face any other problem u can simply reach out to me in discord

**Pull request closed without merging**
