### PR TITLE
make contact us for tindog website and adding a popup thanks for subscribing when someone subscribe the website 

### LINKED ISSUE #1012: [Feature Request]: make a contact section for Tindog website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

a contact us section for tin dog website 

### Use Case

users can use it to contact owners

### Benefits

users can use it to contact owners

### Add ScreenShots

_No response_

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by ANKeshri**
# Title and Issue number 

Title : make contact us for tindog website and adding a popup thanks for subscribing when someone subscribe the website 

Issue No. : #1012 

Code Stack : html css and js

Close #1012 

# Video (mandatory)

image

popup on subscribing :  

https://github.com/user-attachments/assets/757642df-9cf2-48cc-b4d5-bde8b564ed10

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X]  have created a helpful and easy to understand `README.md`
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

### CODE REVIEW

**Comment by ANKeshri** [comment]
@apu52  please review once and merge my pr

**Comment by ANKeshri** [comment]
@apu52 this section is in gradiennt and then there is faq section in my another pr which is white so alternate colour is maintained as per the theme of project .

**Comment by ANKeshri** [comment]
@apu52 I have added popup when someone subscribe the website as shown in video please review it once and merge my pr thank you

**Review by apu52 — APPROVED** [review]
@ANKeshri good work

**Pull request merged**
