### PR TITLE
Drop Down Feature Added

### LINKED ISSUE #799: [Feature Request]: Add ability to select a specific year and month in the calendar
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to request a feature that allows users to jump directly to a specific year and month in the calendar, rather than only navigating month by month using side arrows. This could be implemented with dropdown menus or an input field where users can select or enter the desired year and month.

### Use Case

This feature would be particularly beneficial for users who need to quickly reference or add events in future or past years and months without having to click through each month sequentially. For example, if a user wants to check their schedule for December 2025 while currently viewing June 2024, they could directly jump to the desired date.

### Benefits

Implementing this feature would significantly improve the user experience by making navigation more efficient and user-friendly. It would save users time and make the calendar more versatile for long-term planning.

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by kirti-salini**
Title :Added the ability to select a specific year and month in the calendar

Issue No. :#799

Code Stack : HTML, CSS, JavaScript

Close #799

# Video (mandatory)

After Changes:

https://github.com/apu52/METAVERSE/assets/117555508/0a56c6f4-a32f-4a09-af99-54dc3041eae1

Code Changes:

https://github.com/apu52/METAVERSE/assets/117555508/06f9e71f-1add-4566-a022-33ba8a2b7cfb

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [ ] I'm a GSSOC'24 contributor
- [x] I'm a SSOC'24 contributor

### CODE REVIEW

**Comment by kirti-salini** [comment]
Please review and close this issue

**Comment by kirti-salini** [comment]
Please review my PR and close this issue

**Review by apu52 — APPROVED** [review]
@kirti-salini well changes

**Comment by apu52** [comment]
@kirti-salini please join the OS lead platform (u can get the link from the official SSOC discord page) otherwise I can't assign u points

**Comment by kirti-salini** [comment]
I did it, Please assign me Points

**Pull request merged**
