### PR TITLE
fixed the about page footer and the home page link

### LINKED ISSUE #632: Feature_Request: A number of issues with the current websites
**Is your feature request related to a problem? Please describe.**
- First the home button does not work on the about page because of the link text is out of anchor element.
- footer does not cover the width of the desktop layout.
- The achievement can be improved and centered on mobile as well as desktop.

**Describe the solution you'd like**
- Moving the span element with home text inside anchor tag on about page.
- removing min-width from main container or moving footer out of main container.

**Additional context (Mandatory )**

Screenshots:
as you can see "METAVERSE as secured a position in top 50 maintainer repositories in QUINE HACTOBERFEST challenge" container is not displayed well on mobile.
image

The footer doesn't cover the width on desktop: 
image

***Are you contributing under any open-source program ?***
- GSSOC24'

### PR DESCRIPTION
**Pull request by Stiffpixels**
# Title and Issue number 

Title : fixed the about page footer and the achievement section along with the home page link on the about page and contact page.

Issue No. :#632

Code Stack : html, css

Close #632

# Video (mandatory)

video showcasing the home page link working on about page and responsive change on mobile, tablet and desktop to the same page:  

https://github.com/apu52/METAVERSE/assets/32983571/d5102736-4710-4423-9986-ecaed7fe938f

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**
this issue caused the footer not be rendered properly as you can see in the live version below:
image

the home page link on the about page does not work.
the "r1" label is missing from home page link on contact page.
image

***Are you contributing under any Open-source programme?***
GSSOC24'

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@Stiffpixels This PR have merge conflicts Please try to resolve the issues so That I can merge the PR. Please update(sync) your branch in the fork repo to update the repo. Otherwise I  have already reviewed the PR & your contribution is really working well . Well done

**Review by Stiffpixels — COMMENTED** [review]
reviewed the files

**Comment by Stiffpixels** [comment]
> @Stiffpixels This PR have merge conflicts Please try to resolve the issues so That I can merge the PR. Please update(sync) your branch in the fork repo to update the repo. Otherwise I have already reviewed the PR & your contribution is really working well . Well done

resolved the conflicts please review before more conflicts

**Review by apu52 — APPROVED** [review]
@Stiffpixels Good work .

**Review by apu52 — APPROVED** [review]
good changes

**Pull request merged**
