### PR TITLE
Created a New Cursor Trail effect to Improve UI/UX 

### LINKED ISSUE #968: [Feature Request]: Re-Create Cursor Trail effect to Improve UI/UX
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @apu52 and @heysagnik 

The current cursor animation looks laggy and odd instead I would like add a trail effect to look more interactive, engaging and improve UI/UX, I will ensure to match it to the website design theme

Like this:

https://github.com/user-attachments/assets/841dd647-f990-43c9-b317-2cff2f3f54d1

### Use Case

Increase Users engagement and User experience 

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MastanSayyad**
# Title and Issue number 

- Issue fixes #968 

Code Stack : HTML, CSS, JS

Hey @heysagnik and @apu52 

I have created a cursor trail effect for the website which matches to the website design theme
- It works smooth and fast
- the color is radial gardient of `rgba(73, 232, 247, 0.466)` and `rgba(141, 38, 172, 0.5)`
- added box shadow for glowing effect of mix color `#23bdf5`, `#f523f5` and `#23bdf5`

# Video (mandatory)

https://github.com/user-attachments/assets/ccd46835-3021-470c-a4ca-a9481e6a3b4d

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC'24 contributor

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@apu52 and @heysagnik 

please take a look and review it, also I have one request If possible please increase the level based on the functionalities and feature I have added across all pages of the website!

**Comment by MastanSayyad** [comment]
@apu52 and @heysagnik Please merge this PR

**Review by apu52 — CHANGES_REQUESTED** [review]
@MastanSayyad this PR has merge conflicts .please try to resolve them faster so that I can review the code & will be able to merge it or submit a complete new PR to avoid the merging conflicts

**Comment by MastanSayyad** [comment]
@apu52 I have resolve the conflicts, pls take a look and merge it!

**Comment by MastanSayyad** [comment]
@apu52 and @heysagnik please take a look and merge this PR

**Pull request merged**
