### PR TITLE
Unit_Converter

### PR DESCRIPTION
**Pull request by Jatingupta9120**
# Title and Issue number 

Title :Unit-Converter Project

Issue No. :#61

Code Stack : Html,Css,javascript

Close #<issue_no>

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have updated the Index.html file for my contribution

**Additional context (Mandatory )**
 
- [X] I am a contributor in OSEN open source programme

 
- [X ] I am a contributor in HACTOBERFEST 2023

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
Please go through contributing.md properly. Add a proper readme.md file & also update your project in the index.html.md section

**Comment by Jatingupta9120** [comment]
image
1**.added readme file.**
image
2.**Updated index.html.md**

**Comment by apu52** [comment]
@Jatingupta9120 the deployment link is not working awa I can't see any changes in the index.html.md file
please try to make those changes in a single PR

**Comment by Jatingupta9120** [comment]
I have add file index.html.md now check and merge pr

**Comment by apu52** [comment]
@Jatingupta9120 please resolve the merge conflicts

**Comment by Jatingupta9120** [comment]
@apu52 i have resolve all the issue now check

**Review by apu52 — APPROVED** [review]

**Pull request merged**
