### PR TITLE
UI Enhancement for Age calculator

### LINKED ISSUE #795: [Feature Request]: UI enhancement for age calculator
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature Description

**The UI is not satisfying  as some of the content is missing under css** 
Screenshot from 2024-06-15 20-01-27

**what content are missing** 
Screenshot from 2024-06-15 20-02-12

### Use Case

make the user see the result 

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by HWKDS**
# Title and Issue number 

Title : UI Enhancement fore age calculator 

Issue No. : #795

Code Stack : Html , css

Close #795 

# before:
Screenshot from 2024-06-15 20-01-27

# After:
Screenshot from 2024-06-20 01-37-14

# Video (mandatory)

https://github.com/apu52/METAVERSE/assets/79627715/cc1a5731-ef40-495e-b48f-21066bc44939
# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [ ] I'm a GSSOC'24 contributor
- [x] I'm a SSOC'24 contributor

### CODE REVIEW

**Comment by HWKDS** [comment]
@anuragverma108  considered implementing a dark mode switch, but I believe this theme is more visually appealing than the standard dark and light alternatives.

**Review by apu52 — CHANGES_REQUESTED** [review]
@HWKDS there are some recent changes in this same project .that's why this PR is facing some merging conflicts .please try to resolve the merging conflicts & try to make a new PR .

**Comment by HWKDS** [comment]
> @HWKDS there are some recent changes in this same project .that's why this PR is facing some merging conflicts .please try to resolve the merging conflicts & try to make a new PR .

Will make a new one .
But it Will take some time due to my ongoing examination

**Comment by apu52** [comment]
> > @HWKDS there are some recent changes in this same project .that's why this PR is facing some merging conflicts .please try to resolve the merging conflicts & try to make a new PR .
> 
> Will make a new one . But it Will take some time due to my ongoing examination

no problem .take ur time .I am closing this PR for now . But the issue is still open So u can submit your new PR.

**Pull request closed without merging**
