### PR TITLE
add faq in tindog website 

### LINKED ISSUE #1013: [Feature Request]: make Faq section for TinDog website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

a faq setion for the ewebsite

### Use Case

faq section for this website 

### Benefits

users can clear their doubts regarding to the website 

### Add ScreenShots

https://github.com/user-attachments/assets/12d2ce6b-8991-4d65-bd76-c8e4d4fbf030

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by ANKeshri**
# Title and Issue number 

Title :add faq in tindog website

Issue No. :#1013

Code Stack : htm css

Close #1013

# Video (mandatory)

https://github.com/user-attachments/assets/4e134363-9596-4c73-bf72-6694dd874650

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

### CODE REVIEW

**Comment by ANKeshri** [comment]
@apu52 please review once and merge my pr

**Review by apu52 — APPROVED** [review]
@ANKeshri good work

**Review by apu52 — CHANGES_REQUESTED** [review]
@ANKeshri I have reviewed it . but this PR has some merge conflicts . please try to resolve those otherwise I can't merge this pR

**Comment by ANKeshri** [comment]
@apu52 done

**Review by apu52 — APPROVED** [review]

**Pull request merged**
