### PR TITLE
[Feature Request]: want to improve country guide app i wll almost renew the Ui #852

### LINKED ISSUE #852: [Feature Request]: want to improve country guide app i wll almost renew the Ui
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Make Better Design

### Use Case

it will  improve overall user experience

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by nishant0708**
# Title and Issue number 
Title : Updated Ui Of Country Guide Fully Make it professional 

Issue No. :#852

Code Stack : mern

Close #852 

# Video (mandatory)

https://github.com/apu52/METAVERSE/assets/101548649/c484a4be-156a-43f3-a49b-b375259e8569

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

### CODE REVIEW

**Comment by nishant0708** [comment]
Hey @apu52  @heysagnik  Can You review This pr As promised i have updated Ui of Country Guide

**Comment by nishant0708** [comment]
hey @apu52  please review this pr whenever possible

**Review by apu52 — CHANGES_REQUESTED** [review]
I have reviewed all of your changes & they are really good ....But I can't see any of the changes (https://deploy-preview-940--cute-quokka-b093d8.netlify.app/) in the deployed version of your PR. 
So please check that .Otherwise although I will merge the pR , no changes will be shown in the website made by u

**Comment by nishant0708** [comment]
Hey @apu52 can you tell what changes might help?

**Comment by apu52** [comment]
> Hey @apu52 can you tell what changes might help?

Actually in the Country guide Website(after your changes )  is not loading & not showing up anything. U can check that in the above link. So make sure that what the changes u have made must be shown up in the main website.

**Comment by nishant0708** [comment]
Okay @apu52 I will fix it  today only thanks for responding

**Comment by nishant0708** [comment]
hey @apu52 i tried but nothing is working i am only getting one solution in mind that i could create one html page and host project somewhere else and everything will work fine other than this i cant find solution if you have any solution please let me know because it took alot of time i dont want it to go in waste i hope you understand what i am saying

**Comment by apu52** [comment]
> hey @apu52 i tried but nothing is working i am only getting one solution in mind that i could create one html page and host project somewhere else and everything will work fine other than this i cant find solution if you have any solution please let me know because it took alot of time i dont want it to go in waste i hope you understand what i am saying

YEAH .I UNDERSATND & REALLY RESPECT YOUR EFFORTS . OKK TRY TO HOST THE PROJECT SOMEWHERE ELSE & PUT THE LINK IN THE WEBSITE & ALSO PUT THE LINK IN THE PROJECT FILE ITSELF 7 ALSO PLEASE MENTION IT IN THIS pr . GO AHEAD.

**Comment by nishant0708** [comment]
hey @apu52  I have Done That + I have Added Folder There As well in Case Needed

**Comment by apu52** [comment]
@nishant0708 
image

I can't see . Can u help me???

**Comment by nishant0708** [comment]
> @nishant0708 image
> 
> I can't see . Can u help me???

@apu52 sir Please Check it now i guess it should work

**Review by apu52 — APPROVED** [review]

**Comment by apu52** [comment]
@nishant0708 really great contributions.one of the most great contributions I have ever seen in this repo .Thanks for your valuable contribution. Hope to see more of your great contributions . All the best

**Comment by apu52** [comment]
& please don't call me Sir , I am just a student

**Pull request merged**
