### PR TITLE
feat: Added contact us page in the travel website project .

### LINKED ISSUE #1208: [Feature Request]: Add contact us page in the Travel Website .
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

No action takes place on click of the contact us button on the navbar .

### Use Case

I want to attach a contact us page with the website so that on click of the button contact page is displayed .

### Benefits

_No response_

### Add ScreenShots

Screenshot (968)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by meetarora10**
# Title and Issue number 

Title : Add contact us page in the Travel Website . 

Issue No. : #1208

Code Stack : HTML,CSS

Close #1208

# Video (mandatory)

https://github.com/user-attachments/assets/f88c7961-f363-4cca-a64b-60657645afd9

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
image

@meetarora10 the alignment of this contact us section is not good . Please make this necessary changes

**Comment by meetarora10** [comment]
Ok @apu52

**Comment by meetarora10** [comment]
Done @apu52 
Screenshot (989)
Screenshot (990)

**Review by apu52 — APPROVED** [review]
@meetarora10 good work .

**Pull request merged**
