### PR TITLE
Added styles hovering effect and transitions to blog website

### LINKED ISSUE #759: [Bug]: Adding Styles and hovering effect and animations to the Blog Website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Adding Styles and hovering effect and animations to the Organica website

### Expected behavior

Adding transitions and animations to Blog website

### Add ScreenShots

image

image

image

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by SuhainaFathimaM**
# Title :  Added Styles and hovering effect and animations to the blog website

Issue No. : #759

Code Stack :  HTML, CSS, JavaScript

Close #759

1. Added Light gray background
2. Added styles to the header
3. Added box shadow for Header
4. added color to icons
5. Added transition
6. Added colors on hovering
7. Added position to the background overlay
8. Added a good background overlay to the hero section
9. Added hovering effect on transition to the hl of hero content and text shadow and changed the color
10. Added hovering effect for hl in hero content
11. Added text color to the hut of hero content and add a text shadow and transition effect on hovering
12. Added hovering effects
13. Added a smooth transition function for image transform in hero image
14. Make the image slightly larger on hover
15. Added styles to buttons
16. Add an hovering effect on box shadow on hovering to the buttons
17. added smooth transition effect for image transform unhovering in h card
18. Add a transform on hovering to images
19. Add transition function for V card
20. Added hover effect to the v card
21. add a transition to v card image and added hovering effect to the V card
22. add spacing between cards
23. Dark background for footer and light color for text

# Video (mandatory)

Screenshot 2024-06-15 003223
Screenshot 2024-06-15 003235
Screenshot 2024-06-15 003248

Screenshot 2024-06-15 003300
Screenshot 2024-06-15 003320
Screenshot 2024-06-15 003331
Screenshot 2024-06-15 003352

# Checklist:!
- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

@apu52 I am contributing GSSoC 2024

### CODE REVIEW

**Comment by SuhainaFathimaM** [comment]
@anuragverma108 @apu52 Please merge this PR and label this PR under GSSoC

**Comment by SuhainaFathimaM** [comment]
@anuragverma108 @apu52 Please merge this PR and label this PR under GSSoC.. So I can work on next issue

**Review by apu52 — CHANGES_REQUESTED** [review]
image

After all of your changes the website is really looking messed up I think maybe the CSS file or js file is not connected with the HTML file .Please check all of your changes again

**Comment by SuhainaFathimaM** [comment]
@apu52 Now it works..

**Review by apu52 — CHANGES_REQUESTED** [review]
@SuhainaFathimaM not working till now

**Comment by SuhainaFathimaM** [comment]
Only the css file.. that too I have linked it.. 
@apu52 Please tell me what can I do??

**Comment by SuhainaFathimaM** [comment]
@apu52 Now this style will work.. corrected the error..
image

**Review by apu52 — APPROVED** [review]
@SuhainaFathimaM really well done . The features are really working well now

**Pull request merged**
