### PR TITLE
Added RateUs Page

### LINKED ISSUE #1169: Add a Rate Us Option
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24

### Use Case

It will Enhance User Experience 

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Title :Added Rate Us Page
Issue No. :1169
Code Stack : Html,css
Close #1169

Kindly go through this PR @apu52 

https://github.com/user-attachments/assets/95b740f5-87ac-44e7-9276-2ac932c38b95

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@sailaja-adapa this pR  has some merge conflicts .Please try to fix / resolve the conflicts so that I can review the code & be able to merge it.

**Comment by sailaja-adapa** [comment]
@apu52 I solved the conflicts please go through this PR

**Comment by apu52** [comment]
@sailaja-adapa 

image


after the changes u have made in the last commit the website is looking so much messy , please try to fix that & also the navbar in the rate us page is not working well

**Comment by sailaja-adapa** [comment]
@apu52 So Sorry for that  i will resolve and notify you

**Comment by apu52** [comment]
> @apu52 So Sorry for that i will resolve and notify you

no probs , just ping me here after u have made the necessary changes

**Comment by sailaja-adapa** [comment]
@apu52 I will notify you soon Thank You :)

**Comment by sailaja-adapa** [comment]
@apu52 Once go through this PR and let me if i need to make changes

**Review by apu52 — APPROVED** [review]

**Pull request merged**
