### PR TITLE
Survey form

### LINKED ISSUE #73: Survey Form
**Describe the project you want to add with tech stack**
This is a survey form using HTML & CSS.

**Expected behavior**
We can fill the form and submit it. Basically it is a frontend project.....

**Screenshots (optional)**

**Additional context (Mandatory )**
 
- [X] I am a contributor in OSEN open source programme

 
- [X] I am a contributor in HACTOBERFEST 2023

### PR DESCRIPTION
**Pull request by paulsuryanshu**
Survey form 73

Title : Survey form

Issue No. : #73  

Code Stack : HTML & CSS

Close #73 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have updated the Index.html file for my contribution

**Additional context (Mandatory )**
 
- [X] I am a contributor in OSEN open source programme

 
- [X] I am a contributor in HACTOBERFEST 2023

### CODE REVIEW

**Comment by paulsuryanshu** [comment]
@apu52 Check it and merge it

**Comment by apu52** [comment]
@paulsuryanshu please add your project to index.html.md file

**Review by apu52 — CHANGES_REQUESTED** [review]
.

**Comment by paulsuryanshu** [comment]
@apu52 done

**Comment by apu52** [comment]
@paulsuryanshu Please resolve the merging conflicts

**Comment by paulsuryanshu** [comment]
@apu52 Done

**Comment by apu52** [comment]
@paulsuryanshu Please add your project pics in the index.html.md file

**Comment by apu52** [comment]
@paulsuryanshu Please try to follow the instructions strictly mentioned in contributing.md

**Pull request merged**
