### PR TITLE
fixed the alignment issue for toggle button

### LINKED ISSUE #941: [Bug]: Dark and light mode alignment issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the dark mode button is making the alignment of the site unstable and it's positioning is not good to
please assign the issue to me I can fix that

### Expected behavior

it should be aligned with in the nav bar and should not exceed x axis

### Add ScreenShots

Screenshot (196)
Screenshot (197)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by ChiragShukla222**
# [Bug]: Dark and light mode alignment issue #941

Title :
 [Bug]: Dark and light mode alignment issue
Issue No. :
#941

Close #941

Code Stack : 

Close #<941>

# Video (mandatory)
[

https://github.com/user-attachments/assets/af85b442-c150-4c78-820e-f2e9358c4797

](url)

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC'24 contributor

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@ChiragShukla222 the changes u have made are really good .but I still like the custom design of the toggle button which we already have in the website & I much not like the deign of this PR .
But this issue is still open , if u have farther more good ideas about the toggle button u can submit a new PR on it.

**Comment by ChiragShukla222** [comment]
Hi @apu52 ,

Thank you for your feedback on the toggle button design. I appreciate your input and understand the importance of maintaining consistency with the existing website design.I’m open to further discussions and iterations to ensure we achieve the best possible outcome for the project. If you have any specific aspects of the current toggle button design that you’d like to retain, I would be happy to integrate those elements into the new pr.

**Comment by apu52** [comment]
> Hi @apu52 ,
> 
> Thank you for your feedback on the toggle button design. I appreciate your input and understand the importance of maintaining consistency with the existing website design.I’m open to further discussions and iterations to ensure we achieve the best possible outcome for the project. If you have any specific aspects of the current toggle button design that you’d like to retain, I would be happy to integrate those elements into the new pr.

I can suggest u some UI design of the toggle button . but I just want to u can provide me here some of the other designs u have matching with the website

**Comment by ChiragShukla222** [comment]
sure we can work on that, we'll provide you with the designs as soon as possible.

**Pull request closed without merging**
