### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Jivanjamadar**
Changed positions, width, height and structure of images in doc.

# Title and Issue number 

Title : Setting "Open source images" and "profiles" in right way for increase readability of README.md file

Issue No. : 
#1281

Tech Stack :  
HTML, CSS

Close #<1281>

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [X] Documentation update
- [ ] Add WEB3 project
- [ ] Other (specify): _______________

# Video (mandatory)

https://github.com/user-attachments/assets/5aabc7d3-094b-4d55-82f1-b4c3ff61c95b

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing
- [X] I have Starred the Repository.

# Checklist:(In case of Adding New WEB3 project only)

- [ ] I have made my Commits(of new project) under the  `Projects` folder
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] i have added the image of my project under `asstes/img` folder

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC'24 extended contributor
- [ ] I'm a Winter of Blockchain(WOB'24) contributor
- [X] I'm a Hactoberfest'24 contributor

### CODE REVIEW

**Comment by Jivanjamadar** [comment]
@apu52 Is it approved changes in README.md file

**Comment by Jivanjamadar** [comment]
@apu52 It'salmost 3 days has been past but no update on acceptance. Please, review it & give me update.

**Comment by Jivanjamadar** [comment]
@sanjay-kv Sir please inform @apu52 that it's almost week but I haven't got any response from him.

**Review by apu52 — APPROVED** [review]
@Jivanjamadar good work

**Pull request merged**
