### PR TITLE
changed netflix project

### LINKED ISSUE #949: [Feature Request]: Enhancement of the netflix footer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the footer of the Netflix, there is no proper alignment and description 

### Use Case

The footer is not the same as the official footer so we have to change the footer

### Benefits

_No response_

### Add ScreenShots

please assign me @pa

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by jayanththalla**
# Title and Issue number 

Title: Change the Netflix clone project 

Issue No. : #949 

Code Stack :  HTML,CSS

Close #949 

# Video (mandatory)

https://github.com/user-attachments/assets/d1edea1a-ab0d-4eda-99bd-0786c0f2ce1c

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

### CODE REVIEW

**Comment by jayanththalla** [comment]
There is no conflicts in my pr but i not know why it is happening can u say how to solve the issue
image

**Comment by apu52** [comment]
> There is no conflicts in my pr but i not know why it is happening can u say how to solve the issue image

there is some recent changes as some new PR has been merges regarding this same project .I would like to request you to close this PR & after updating your branch , submit your new PR.

**Review by apu52 — CHANGES_REQUESTED** [review]
@jayanththalla please solve the resolve conflicts.

**Comment by jayanththalla** [comment]
I tried but it not showing the resolved conflict button i don't want the js only i done with HTML CSS part only can u guide me to solve please @apu52

**Comment by apu52** [comment]
> I tried but it not showing the resolved conflict button i don't want the js only i done with HTML CSS part only can u guide me to solve please @apu52

The conflicts are really complex to solve so I would like to suggest u to better to close this PR & submit a complete new PR on this

**Pull request closed without merging**
