### PR TITLE
Tindog: Startup Website

### LINKED ISSUE #35: Tindog: A startup Website
**Describe the project you want to add with tech stack**
Tindog, a startup website; it has best priced plans for entertainment of dogs of different breeds; it has matches, messeges etc.
Screenshot 2023-10-16 143401
Screenshot 2023-10-16 143420
Screenshot 2023-10-16 143431

Tech stack: Bootstrap is used and CSS animations are added

**Expected behavior**
The website will have separate sections for title, features, testimonial, pricing, footer, along with animations using css.

**Screenshots (optional)**
I have added some screenshots.

**Additional context (optional )**
This can be taken as a project and can be build upon in future; many more features can be added.

### PR DESCRIPTION
**Pull request by RAGHAVS1304**
# Title and Issue number 

Title :Tindog: Startup Website

Issue No. : 35

Code Stack : HTML, CSS, Bootstrap

Close #35

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have updated the Index.html file for my contribution

### CODE REVIEW

**Comment by RAGHAVS1304** [comment]
Bro i have again raised the PR, after resolving some problem,please review it.
Thanks

**Comment by 5h0ov** [comment]
> Bro i have again raised the PR, after resolving some problem,please review it. Thanks

the deployment link isn't working could you remove the ./css/ part as there is no such css folder present:

image

**Comment by 5h0ov** [comment]
@RAGHAVS1304 looks good! Thanks for contributing!

**Comment by RAGHAVS1304** [comment]
Thanks sir, for your support.👍
I am willing to make more contributions in future.

**Pull request merged**
