### PR TITLE
Added Cursor Animation | Issue #1243

### LINKED ISSUE #1243: Feature Request : Missing Animation of Mouse hover on contributors page
@sanjay-kv @Stiffpixels @OkenHaha @KeyurGK 
I am going to add the exact same animation of mouse hover on the page of contributors to match the page with the all pages and the theme of the website.

Please assign the issue to me.

https://github.com/user-attachments/assets/bf9b2922-8e2e-4f46-9e1a-6137e1d88dcb

### PR DESCRIPTION
**Pull request by Shariq2003**
# Title and Issue number 

Title : Added Cursor Animation | Issue #1243

Issue No. : #1243 

Tech Stack : 

https://github.com/user-attachments/assets/53826df8-5f32-41ff-aba8-9c704a6b2357

Close #1243 

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Add WEB3 project
- [ ] Other (specify): _______________

# Video (mandatory)

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing
- [X] I have Starred the Repository.

# Checklist:(In case of Adding New WEB3 project only)

- [ ] I have made my Commits(of new project) under the  `Projects` folder
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] i have added the image of my project under `asstes/img` folder

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC'24 extended contributor
- [ ] I'm a Winter of Blockchain(WOB'24) contributor
- [X] I'm a Hactoberfest'24 contributor

### CODE REVIEW

**Comment by Shariq2003** [comment]
@apu52 sir, please merge this

**Comment by Shariq2003** [comment]
@apu52 sir, please review and merge

**Review by apu52 — CHANGES_REQUESTED** [review]
@Shariq2003 this pr is facing some merge conflicts please try to resolve this so that I can review & merge this pr

**Comment by Shariq2003** [comment]
> @Shariq2003 this pr is facing some merge conflicts please try to resolve this so that I can review & merge this pr

Okay fixing

**Comment by Shariq2003** [comment]
> @Shariq2003 this pr is facing some merge conflicts please try to resolve this so that I can review & merge this pr

@apu sir, review and merge this please

**Review by apu52 — APPROVED** [review]
@Shariq2003 good work

**Pull request merged**
