### PR TITLE
Ping Pong Game

### LINKED ISSUE #308: Ping Pong Game
### Project title
Ping Pong Game

### Project Description
Ping pong, also known as table tennis, is a popular indoor sport in which two or four players hit a lightweight ball back and forth across a table using small, handheld rackets.

### Web stack
HTML , CSS AND JavaScript.

### Screenshot(mandatory)

Screenshot 2023-12-18 143255

#### Are you contributing under any open-source program ?
I am working under codepeak'23.

### PR DESCRIPTION
**Pull request by Mayank77maruti**
# Title and Issue number 

Title : Ping Pong Game 

Issue No. : #308 

Code Stack : HTML , CSS and JavaScript.

Close  #308 

# Video (mandatory)

Uploading ping pong vid 3.mp4…

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have updated the `projectData.json` file for my contribution
- [x] I have added the img of my project in the `assets/img` section

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***
I am working under codepeak'23

### CODE REVIEW

**Review by 5h0ov — APPROVED** [review]

**Comment by 5h0ov** [comment]
@Mayank77maruti  could you put the files in properly in the folder you created for your project for example:

image


and change ur .html to index.html or else its not loading

**Comment by Mayank77maruti** [comment]
Hey @5h0ov , I have fixed the issue , If there is any further issue please do let me know.

**Comment by 5h0ov** [comment]
could you add the audio css js folder in the folder with the html and adjust the address accordingly AND change ur Ping Pong Game.html to index.html

**Comment by Mayank77maruti** [comment]
Screenshot 2023-12-19 094630
I have changed ping pong html to index.html and should i make a different folder for audio along with html file

**Comment by 5h0ov** [comment]
> Screenshot 2023-12-19 094630 I have changed ping pong html to index.html and should i make a different folder for audio along with html file

ok! thanks for contributing!

**Pull request merged**
