### PR TITLE
[BUG FIX] Renamed the Codeforces API Project to its actual name- Rock Paper Scissors game

### LINKED ISSUE #947: [Bug]: The Codeforces API Project has Rock Paper Scissors game in it
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The project titled `115. Codeforces API` has rock paper scissors game in it, instead of what the name suggests. 

### Expected behavior

The title should display the correct name of the project i.e. `Rock Paper Scissors-2` instead of the misleading `Codeforces API` name

### Add ScreenShots

image
image

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by agrawal-yash**
# Title and Issue number 

Title : Renaming the  Codeforces API Project to its actual name- Rock Paper Scissors game

Issue No. : #947 

Code Stack : HTML, CSS, JS, JSON

Close #947 

# Video (mandatory)

image

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
why this Hotstar Clone Commit present here?? please omit these changes as it is unnecessary in this pR

**Review by apu52 — APPROVED** [review]
these changes are working well

**Review by apu52 — CHANGES_REQUESTED** [review]
why this Hotstar Clone Commit present here?? please omit these changes as it is unnecessary in this pR @agrawal-yash

**Comment by agrawal-yash** [comment]
@apu52 Sorry for the extra commit. I have successfully removed that commit and no additional file is changed now. Please review and merge the PR.

**Review by apu52 — APPROVED** [review]

**Comment by apu52** [comment]
> @apu52 Sorry for the extra commit. I have successfully removed that commit and no additional file is changed now. Please review and merge the PR.

no problem it's ok . thanks for your valuable contribution

**Pull request merged**
