### PR TITLE
New secret keeper project added

### LINKED ISSUE #547: Secrets keeper with encryption and decryption using nodejs
### Project title
Secret Keeper

### Project Description
A website that can be used to store secrets of your using database,  and in the database it will be stored using encryption and decryption using any node packages, so secrets will be safe even if database is exposed or got access by someone 

### Web stack
nodejs runtime, js, css, html, bootstrap maybe

### Screenshot(mandatory)

well its not done yet so i dont have any screenshot, so ill be completing it till 28 date for sure

### Additional Context(mandatory)
Sounds like a simple to-do-list like project but it is different, it will be more than that, ill complete it till 28
#### Are you contributing under any open-source program ?

codepeak 2023
<hr/>

### PR DESCRIPTION
**Pull request by Sami3160**
# Title and Issue number 

Title :secret keeper

Issue No. :
#547 
Code Stack : 
js, html, css, crypto api
Close #547 

# Video (mandatory)

https://github.com/apu52/METAVERSE/assets/110652247/9e3ab6e8-9f65-4cdd-b2d0-66baeb59976a

Screenshot_20231228_230730

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x]  I have updated the `projectData.json` file for my contribution
- [x] I have added the img of my project in the `assets/img` section

**Additional context (Mandatory )**
the website uses onmline web api of crypto, well i wanted to use nodejs, but their were some version related issues with integration of decryption of secrets, so i used scrypto web api
***Are you contributing under any Open-source programme?***

codepeak 2023

### CODE REVIEW

**Comment by apu52** [comment]
@Sami3160 Where is the Video prototype??

**Comment by Sami3160** [comment]
> @Sami3160 Where is the Video prototype??

Sry, in hurry I forgot, wait I'll upload in few seconds

**Comment by apu52** [comment]
> > @Sami3160 Where is the Video prototype??
> 
> Sry, in hurry I forgot, wait I'll upload in few seconds

Where is the img attached in assets/image folder

**Comment by Sami3160** [comment]
> @Sami3160 Where is the Video prototype??

Yeah sir it is now uploaded

**Comment by Sami3160** [comment]
> > > @Sami3160 Where is the Video prototype??
> > 
> > 
> > Sry, in hurry I forgot, wait I'll upload in few seconds
> 
> Where is the img attached in assets/image folder

yeah it is their, with name images/Screenshot_20231228_230730.png

**Comment by apu52** [comment]
> > > > @Sami3160 Where is the Video prototype??
> > > 
> > > 
> > > Sry, in hurry I forgot, wait I'll upload in few seconds
> > 
> > 
> > Where is the img attached in assets/image folder
> 
> yeah it is their, with name images/Screenshot_20231228_230730.png

It shouln't be in the images folder. The img must be in the assets/img folder. Check it

**Comment by Sami3160** [comment]
> > > > > @Sami3160 Where is the Video prototype??
> > > > 
> > > > 
> > > > Sry, in hurry I forgot, wait I'll upload in few seconds
> > > 
> > > 
> > > Where is the img attached in assets/image folder
> > 
> > 
> > yeah it is their, with name images/Screenshot_20231228_230730.png
> 
> It shouldn't be in the images folder. The img must be in the assets/img folder. Check it

dammmm...waiititt
illl fix

**Comment by Sami3160** [comment]
> > > > > > @Sami3160 Where is the Video prototype??
> > > > > 
> > > > > 
> > > > > Sry, in hurry I forgot, wait I'll upload in few seconds
> > > > 
> > > > 
> > > > Where is the img attached in assets/image folder
> > > 
> > > 
> > > yeah it is their, with name images/Screenshot_20231228_230730.png
> > 
> > 
> > It shouldn't be in the images folder. The img must be in the assets/img folder. Check it
> 
> dammmm...waiititt illl fix

@apu52 ok sir, every thing is well... img added with name secret.png

**Review by apu52 — APPROVED** [review]

**Pull request merged**
