### PR TITLE
Fixed navbar at top and add hamburger menu for mobile screen

### LINKED ISSUE #1221: Fix Navbar at top and make it responsive
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Navbar should be fixed at top and should be responsive

### Expected behavior

image

### Add ScreenShots

_No response_

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Utsavladia**
# Title and Issue number 
Fixed navbar at top and added hamburger menu #1221 

Title :

Issue No. : #1221 

Code Stack : 

Close #1221 

# Video (mandatory)
image
image

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

### CODE REVIEW

**Comment by Utsavladia** [comment]
@apu52 
Kindly review this one so I can merge conflicts

**Review by apu52 — CHANGES_REQUESTED** [review]
@Utsavladia this PR has some merge conflicts. Please try to resolve the conflicts ASAP so that I can review the code & be able to merge it.

**Comment by Utsavladia** [comment]
@apu52 
Resolved ✅

**Comment by Utsavladia** [comment]
@apu52 
Kindly mrege this PR before GSSOC ends 😌

**Review by apu52 — CHANGES_REQUESTED** [review]
image


@Utsavladia the navbar is not looking good in your PR , it's moving along the scrolling . Please try to resolve it ASAP.& also in the responsive section I can't access the navabar...Please also check it.

**Comment by Utsavladia** [comment]
@apu52 
fixed the navbar at top

image

**Review by apu52 — APPROVED** [review]
@Utsavladia good work

**Comment by Utsavladia** [comment]
@apu52 There is some large issue with the light theme for navbar I will have analyse it and it will take time
meanwhile thankyou for merging before time 
I will fix it if you want in the new issue..

**Comment by apu52** [comment]
> @apu52 There is some large issue with the light theme for navbar I will have analyse it and it will take time meanwhile thankyou for merging before time I will fix it if you want in the new issue.. kindly reply me if you want me to fix this issue and make the website better..

yeah . u can fix it . Now the website is also not working. U can try to raise new issue pointing this .

**Pull request merged**
