### PR TITLE
added check for empty tasks

### LINKED ISSUE #843: [Bug]: Empty Tasks in To-Do List Project
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

You can add empty tasks to the To-Do List Project. Validation checks are missing

### Expected behavior

Empty tasks should not be there.

### Add ScreenShots

image

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by abckhush**
# Title and Issue number 

Title : To_Do_List_Project

Issue No. : 843

Close #843 

# Video (mandatory)

image

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@abckhush there is some conflicts in the PR .please try to resolve the conflicts so that I can review the PR & merge the PR

**Comment by abckhush** [comment]
@apu52 Kindly check now.

**Review by apu52 — CHANGES_REQUESTED** [review]
@abckhush why this unnecessary commits present in this PR??
I suggest you to delete this commits from this PR/branch .
otherwise I can't assign u points & merge this PR

**Review by apu52 — APPROVED** [review]
ok

**Review by apu52 — APPROVED** [review]
@abckhush well made changes .thanks

**Pull request merged**
