### PR TITLE
Made Nav Bar Responsive for mobile view also

### LINKED ISSUE #1144: [Feature Request] : Making Nav bar Responsive For Mobile Screen Also
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Making Nav Bar Responsive for mobile view also

### Use Case

Nav Bar for mobile  view

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
# Title and Issue number 

Title : made Nav Bar Responsive for mobile Displays Also

Issue No. :#1144 

Code Stack : HTML , CSS , JS

Close #1144 

# Video (mandatory)

image

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@apu52 Can you Please Review the PR Soon 
Label is under Level 3 Please 🙂

**Comment by Saipradyumnagoud** [comment]
@apu52 Can You Please Review The PR soon

**Review by apu52 — CHANGES_REQUESTED** [review]
image

After the changes u have made the images of the projects are not loading in this website .please check it.

**Comment by Saipradyumnagoud** [comment]
> image
> 
> After the changes u have made the images of the projects are not loading in this website .please check it.

Yes I will look into them

**Comment by Saipradyumnagoud** [comment]
@apu52 I am able to the images
image

i dont know why you arent able to see

**Comment by apu52** [comment]
> @apu52 I am able to the images image
> 
> i dont know why you arent able to see

yess .now it's working

**Review by apu52 — APPROVED** [review]

**Pull request merged**
