### PR TITLE
 Age calculator

### LINKED ISSUE #831: [Bug]: Age Calculator not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the age calculator does not give response

https://github.com/apu52/METAVERSE/assets/168094736/aff1f602-de40-4479-bd0c-96838846f76e

### Expected behavior

https://github.com/apu52/METAVERSE/assets/168094736/02e12e5b-5669-4b15-b637-8f4e26346bc9

### Add ScreenShots

_No response_

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by puneet426**
# 831

Title : Age Calculator

Issue No. :#831

Code Stack : 

Close #831

Before

https://github.com/apu52/METAVERSE/assets/168094736/52da14a4-ab2c-473c-9dae-8a18ba6f2a56

After

https://github.com/apu52/METAVERSE/assets/168094736/319b9d79-3180-425c-ae4f-b8c111cfaf42

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

### CODE REVIEW

**Comment by puneet426** [comment]
hello @heysagnik please merge it and level

**Comment by puneet426** [comment]
@apu52 please merge this request as it change full UI of the age calculator

**Comment by puneet426** [comment]
@apu52 level it as level 3

**Review by pt-78190 — APPROVED** [review]

**Comment by puneet426** [comment]
Add level on it and merge

**Comment by puneet426** [comment]
@heysagnik please review it

**Review by apu52 — CHANGES_REQUESTED** [review]
@puneet426 there is some recent changes in the age calculator .that's why this PR is facing some merging conflicts . please try to raise a complete new PR .

**Pull request closed without merging**
