### PR TITLE
Bakery Website

### LINKED ISSUE #403: Bakery Shop Landing webpage
### Project title
Bakery Shop landing web page

### Project Description
A webpage where bakery can sell their products .

### Web stack
HTML , CSS AND JAVASCRIPT

### Screenshot(mandatory)
BAKSHOP

#### Are you contributing under any open-source program ?
I am working under codepeak'23

### PR DESCRIPTION
**Pull request by Mayank77maruti**
# Title and Issue number 

Title : Bakery

Issue No. : #403 

Code Stack : HTML , CSS AND JAVASCRIPT

Close #403 

# Video (mandatory)

Uploading BAKERYVID.mp4…

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have updated the `projectData.json` file for my contribution
- [x] I have added the img of my project in the `assets/img` section

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***
I am working under codepeak'23.

### CODE REVIEW

**Comment by shruti-sen2004** [comment]
@Mayank77maruti Please provide the demo video

**Comment by shruti-sen2004** [comment]
Also, resolve the merge conflict.

**Comment by Mayank77maruti** [comment]
https://github.com/apu52/METAVERSE/assets/125661248/bc1a83ec-353e-43b2-bd86-ef912eb8a58d

**Comment by shruti-sen2004** [comment]
@Mayank77maruti please make the PR properly...there are two projects added to this pr ...please fix it

**Comment by Mayank77maruti** [comment]
Hey @shruti-sen2004 , In the recent commit i have made the PR correctly.

**Review by shruti-sen2004 — APPROVED** [review]

**Pull request merged**
