### PR TITLE
lyrics functionality

### LINKED ISSUE #851: Lyrics app not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The bug is that when we click get lyrics we don't fetch the lyrics. <br> kindly assign this issue to me

### Expected behavior

Probable issue is that the website is unable to fetch the lyrics as shown in the below provided screenshot.

### Add ScreenShots

image

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MetiUmashri**
# Title and Issue number 
Title :Lyrics app not working 

Issue No. : #851 

Code Stack : Updated the script.js , css file along with Readme.md

Close #851

# Video (mandatory)
Before
image

Updated 
image

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

Previously Get lyrics was not working in which it has been fixed here

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC'24 contributor
- [] I'm a SSOC'24 contributor

### CODE REVIEW

**Comment by MetiUmashri** [comment]
@apu52 please review and merge my pr

**Comment by MetiUmashri** [comment]
Could you please change the label from SSOC'24 to GSSOC'24

**Comment by apu52** [comment]
> Could you please change the label from SSOC'24 to GSSOC'24

u are contributing under GSSOC'24 or SSOC'24??? 
Then fill up the issue form properly

**Comment by MetiUmashri** [comment]
@apu52 done, could you please merge the pull request

**Review by apu52 — APPROVED** [review]
@MetiUmashri good work

**Pull request merged**
