### PR TITLE
hamburger functionality

### LINKED ISSUE #1269: [Bug]: hamburger is not working in small screen
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/user-attachments/assets/fcfc3b9c-1a2b-4efe-a57e-9fabe7345988

The hamburger is not working in small screen sizes it affects the User Experience.

### Expected behavior

The menu should dropped down when hamburger is clicked . 

### Add ScreenShots

_No response_

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by srishti023**
#1269 hamburger is not working in small screen problem solved

Title :  hamburger is not working in small screen problem solved

Issue No. : #1269 

Close #1269
before:

https://github.com/user-attachments/assets/b2b59512-8690-464f-9429-fe1d3545041f

After

https://github.com/user-attachments/assets/50f4d3a7-6f1a-4357-b16a-cbec8e0fc397

# Type of PR

- [x ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Add WEB3 project
- [ ] Other (specify): _______________

# Checklist:

- [x ] I have mentioned the issue number in my Pull Request.
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have gone through the  `contributing.md` file before contributing
- [ x] I have Starred the Repository.

# Checklist:(In case of Adding New WEB3 project only)

- [ ] I have made my Commits(of new project) under the  `Projects` folder
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] i have added the image of my project under `asstes/img` folder

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC'24 extended contributor
- [x] I'm a Winter of Blockchain(WOB'24) contributor
- [x] I'm a Hactoberfest'24 contributor

### CODE REVIEW

**Comment by srishti023** [comment]
hey @apu52 can you please merge my commit or if any further changes needed please let me know!

**Review by apu52 — CHANGES_REQUESTED** [review]
@srishti023 this pr is facing some merge conflicts please try to resolve this so that I can review & merge this pr

**Review by apu52 — CHANGES_REQUESTED** [review]
image

the whole pr is working well but as I can see there is some tends to invisible letter codes above the search bar , please try to omit/delete the code lines

**Comment by aslams2020** [comment]
This PR has been merged by the GSSoC team 
here - https://github.com/sanjay-kv/Open-source-Practice/pull/1415


 **Don't add labels to it now.**
You'll get the points in the leaderboard update.

**Comment by apu52** [comment]
@aslams2020 what should I do now , will i merge this PR & add labels or not??

**Comment by aslams2020** [comment]
If you want these changes you can merge it without any labels.

Otherwise close this

**Pull request closed without merging**
