### PR TITLE
Floating Aninmation Added

### PR DESCRIPTION
**Pull request by Damini2004**
# Title and Issue number 

Title : Floating Aninmation Added

Issue No. : #1007 

Code Stack : 

Close #<issue_no> #1007 

# Video (mandatory)

https://github.com/user-attachments/assets/cf44b637-6395-41b4-b790-df793c171a17

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

### CODE REVIEW

**Comment by Damini2004** [comment]
@apu52 Kindly enhance the level

**Review by apu52 — APPROVED** [review]
@Damini2004 thats really good

**Comment by Damini2004** [comment]
@apu52 can you increase the level and assign other issue to me.

**Comment by apu52** [comment]
> @apu52 can you increase the level and assign other issue to me.

actually I have reviewed as LEVEL 1 
& regarding the issue can u please provide me the link of the issue here so that I can easily assign u

**Comment by Damini2004** [comment]
No Problem 
https://github.com/apu52/METAVERSE/issues/1009
https://github.com/apu52/METAVERSE/issues/1010
Assign this issue to me.

**Pull request merged**
