### PR TITLE
Log in page

### LINKED ISSUE #74: LogIn Pge
**Describe the project you want to add with tech stack**
This is project based on html and css..

**Expected behavior**
Frontend project of a log in page

**Screenshots (optional)**

**Additional context (Mandatory )**
 
- [X] I am a contributor in OSEN open source programme

 
- [X] I am a contributor in HACTOBERFEST 2023

### PR DESCRIPTION
**Pull request by paulsuryanshu**
LogIn page 74

Title : LogIn Page

Issue No. : #74 
Code Stack : HTML & CSS

Close #74 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have updated the Index.html file for my contribution

**Additional context (Mandatory )**
 
- [X] I am a contributor in OSEN open source programme

 
- [X] I am a contributor in HACTOBERFEST 2023

### CODE REVIEW

**Comment by paulsuryanshu** [comment]
@apu52 check it and merge it

**Review by apu52 — CHANGES_REQUESTED** [review]
@paulsuryanshu Please add your project into index.html.md file

**Comment by apu52** [comment]
@paulsuryanshu please resolve the conflicts

**Comment by paulsuryanshu** [comment]
@apu52 Done

**Comment by apu52** [comment]
image

**Comment by paulsuryanshu** [comment]
@apu52 done

**Comment by paulsuryanshu** [comment]
@apu52 done

**Comment by apu52** [comment]
@paulsuryanshu Please try to follow the instructions strictly mentioned in contributing.md

**Pull request merged**
