### PR TITLE
title and icon added

### LINKED ISSUE #860: [Feature Request]: Add title and icon
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add the title and icon to the anime list project.

### Use Case

This makes completes the anime list project

### Benefits

_No response_

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by chaanakyaaM**
# Title and Issue number 

Title :Title and icon added to anime list

Issue No. : #860

Code Stack : Html

Close #860

# Video (mandatory)

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@chaanakyaaM in the PR deployed link (https://deploy-preview-877--cute-quokka-b093d8.netlify.app/) the crunchyoll-clone is showing that the page link is broken . please look into this matter

**Comment by chaanakyaaM** [comment]
ok i will fix it.

**Comment by apu52** [comment]
image

the page link is still broken , so I can't see any of your changes .please try to fix it.Better submit a new PR

**Comment by chaanakyaaM** [comment]
Kindly review the PR and let me know if it is working or not.

**Review by apu52 — COMMENTED** [review]
@chaanakyaaM it's still not working

**Pull request closed without merging**
