### PR TITLE
Add Sign-In/Sign-Up Functionality with Menu and Database Integration

### LINKED ISSUE #859: Adding Signup/Login Functionality and Database Integration
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implement signup/login functionality, including **Google sign-up/sign-in**, and integrate a **database for user management** on the book review website. This enhancement will improve user engagement, enable personalized experiences, and lay the groundwork for future feature development.

### Use Case

- **Improved User Experience:** Users can create accounts to personalize their interactions, save favorite books, and engage in discussions.

- **Enhanced Security:** Secure authentication mechanisms ensure user data privacy and protection.

- **Advanced Features:** Enables features such as personalized recommendations, user-generated content (reviews, comments), and notifications.

- **Scalability:** A database will support the storage and retrieval of user data efficiently as the platform grows.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by gayatri-p786**
# Title: Add Sign-In/Sign-Up Functionality with Menu and Database Integration

Issue No. : #859 

Code Stack : JavaScript, HTML, CSS, Firebase

Close #859 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`.
- [X] I have gone through the `contributing.md` file before contributing.

**Additional context (Mandatory )**

This pull request introduces comprehensive authentication functionality including sign-in, sign-up, and menu updates based on user authentication state. It also integrates user data storage and retrieval with Firebase Firestore.

***Are you contributing under any Open-source programme?***

- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor

**Changes Made:**

1. **Sign-Up Functionality:**
   - Added `signup.js` to handle user registration.
   - Created a form for user registration with email, password, and Google sign-up options.
   - Stored additional user information (name, username) in Firestore.

2. **Sign-In Functionality:**
   - Added `signin.js` for user login with email/password and Google sign-in options.
   - Implemented session persistence for user authentication.

3. **Menu Updates:**
   - Updated `index.html` to show/hide menu items based on user authentication state.
   - Added a dropdown menu for the profile with options to edit profile and sign out.
   - Implemented `main.js` to handle dynamic display of menu items based on authentication.

4. **Database Integration:**
   - Utilized Firebase Firestore to store and retrieve user data.
   - Ensured user data is correctly fetched and displayed in the profile dropdown.

5. **CSS Styling:**
   - Styled the dropdown menu for the profile.
   - Ensured consistent styling across sign-in/sign-up forms and the dropdown menu.

**Summary of Changes:**
- Added `signup.js` and `signin.js` for handling user registration and login.
- Integrated Firebase Authentication and Firestore for user management.
- Updated `index.html` to dynamically display menu options based on authentication state.
- Styled the profile dropdown menu.
- Implemented session persistence for user authentication.

**Testing:**
- Tested sign-up and sign-in functionalities with both email/password and Google sign-in.
- Verified session persistence and user state across different pages.
- Ensured the profile dropdown menu is displayed correctly for authenticated users.

**Notes:**
- Make sure to configure your Firebase project and update `firebaseConfig.js` with your project details.
- Additional CSS adjustments may be needed to match your overall site design.

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@gayatri-p786 the changes u have made is not showing in the Deployed version of the book review project . Can you please look into the matter ....or can u please provide the prototype video / ss about the features u have added in this project??

**Comment by gayatri-p786** [comment]
Hi @apu52 the changes I have made are currently on my forked repository. If you approve the pull request, they can be merged into the main repository and subsequently deployed.

**Comment by gayatri-p786** [comment]
Here is the video of sign up/sign in function: 

https://github.com/apu52/METAVERSE/assets/64575332/c2a818a8-75e4-4977-ac8b-18935800ff3e

**Comment by apu52** [comment]
> Hi @apu52 the changes I have made are currently on my forked repository. If you approve the pull request, they can be merged into the main repository and subsequently deployed.

Ok Let me Clear . I can see what are your changes through the Deployed link available in the PR (https://deploy-preview-869--cute-quokka-b093d8.netlify.app/) . Here u can see in the book review page it's showing the link is broken . So I am requesting u to look into this matter. Otherwise although I will merge your PR , no changes will be shown in the main website

Otherwise the changes u have made are really great . Just look into this matter

**Comment by gayatri-p786** [comment]
@apu52 I have made the changes. Now the page can be seen in the preview. Just a note that I am not uploading my firebase config secrets that is why this will not perform the same as in video. Please let me know if you can provide these or the PR can be merged without my configs.

**Comment by apu52** [comment]
> @apu52 I have made the changes. Now the page can be seen in the preview. Just a note that I am not uploading my firebase config secrets that is why this will not perform the same as in video. Please let me know if you can provide these or the PR can be merged without my configs.

@gayatri-p786 yes.I understand . there is no need to share your config . Later on I will work on it. For now I am merging your PR under SSOC

**Pull request merged**
