### PR TITLE
Restaurant Website Frontend Project is added.

### LINKED ISSUE #96: A Simple Restaurant Website Using HTML and CSS
**Describe the project you want to add with tech stack**

This is a simple site that is made using HTML and CSS properties. This site mainly uses the concept of grid property of CSS. 

**Expected behavior**

This is properly working as expected 
**Screenshots (optional)**

1
Screenshot (200)
2
Screenshot (201)
3
Screenshot (202)
4
Screenshot (203)

**Additional context (Mandatory )**
 
- [x] I am a contributor to the OSEN open-source program

 
- [x] I am a contributor to HACTOBERFEST 2023

I want to work on this issue

### PR DESCRIPTION
**Pull request by Suraj-kumar00**
# Title and Issue number 

Title :
Restaurant Website 
Issue No. : #96 
Code Stack : 
HTML CSS
Close #96 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have updated the Index.html file for my contribution

**Additional context (Mandatory )**
 
- [X] I am a contributor in OSEN open source programme

 
- [X] I am a contributor in HACTOBERFEST 2023

### CODE REVIEW

**Comment by apu52** [comment]
@Suraj-kumar00 please try to add your project in index.html.md file

**Review by apu52 — CHANGES_REQUESTED** [review]
.

**Comment by Suraj-kumar00** [comment]
> @Suraj-kumar00 please try to add your project in index.html.md file

Hi @apu52 I did please look and merge.

**Comment by apu52** [comment]
@Suraj-kumar00 Please resolve the merge conflicts

**Comment by Suraj-kumar00** [comment]
> @Suraj-kumar00 Please resolve the merge conflicts

Done ✅

**Review by apu52 — APPROVED** [review]

**Pull request merged**
