### PR TITLE
Added Jokes App

### LINKED ISSUE #500: Joke Generator
### Project title
Joke Generator

### Project Description
Fetches Jokes using API

### Web stack
HTML,CSS,JS

### Screenshot(mandatory)

Jokes

#### Are you contributing under any open-source program ?
Codepeak-23

<hr/>

### PR DESCRIPTION
**Pull request by YashSachan2**
# Title and Issue number 
Title : Jokes App

Issue No. : #500 

Code Stack : HTML,CSS,JS

Close #500 

# Video (mandatory)

https://github.com/apu52/METAVERSE/assets/122620769/0d989199-5ab0-4267-ba78-5486a6137077

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have updated the `projectData.json` file for my contribution
- [x] I have added the img of my project in the `assets/img` section

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***
Codepeak-23

### CODE REVIEW

**Review by 5h0ov — APPROVED** [review]

**Comment by 5h0ov** [comment]
@YashSachan2  the tik tok clone is also present in ur PR can you remove that folder?

**Comment by YashSachan2** [comment]
Actually I have made pr for two project  for two issues thats why tinder clone is also present.So should I make two separate pr or combine them in one?

**Comment by 5h0ov** [comment]
> Actually I have made pr for two project for two issues thats why tinder clone is also present.So should I make two separate pr or combine them in one?

it would be better to make 2 seperate PR for each of them :)

**Comment by 5h0ov** [comment]
if you could remove the tinder folder from this PR i can merge this under jokes app

**Comment by YashSachan2** [comment]
Making the changes

**Comment by YashSachan2** [comment]
@5h0ov I have made a new pr for jokes app.Please review

**Comment by 5h0ov** [comment]
> @5h0ov I have made a new pr for jokes app.Please review

oh ok do i close this one then?

**Comment by YashSachan2** [comment]
Yes

**Pull request closed without merging**
