### PR TITLE
Blog Website - GreatZone UI Improved

### LINKED ISSUE #814: [Feature Request]: Improve the UI of Blog Website - GreatZone
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The UI of the Blog Website is not so attractive. So I want to improve its UI

### Use Case

For user experience

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Sanglap-Halder**
# Title and Issue number 

Title : Blog Website - GreatZone UI Improved

Issue No. : 814

Code Stack : 

Close #814

# Video (mandatory)

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**
### **Before->**
BeforeImg

### **After->**
AfterImg

***Are you contributing under any Open-source programme?***

- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor

### CODE REVIEW

**Review by apu52 — APPROVED** [review]
@Sanglap-Halder really great changes .

**Comment by Sanglap-Halder** [comment]
@apu52 I have already joined the OS lead platform. You can merge the PR and give me points based on my work.

And why have you added "help wanted" tag? Did I missed something?

**Comment by Sanglap-Halder** [comment]
I have also made the PR #813 Age Calculator UI Enhanced.
There you told me to join the OS Lead Platform and I joined after you said. Please add that PR also to my score.

**Comment by apu52** [comment]
> @apu52 I have already joined the OS lead platform. You can merge the PR and give me points based on my work.
> 
> And why have you added "help wanted" tag? Did I missed something?

I just have added the label for my clarification . Don't worry . Now as u have joined the OS platform I can assign u points

**Comment by apu52** [comment]
> I have also made the PR #813 Age Calculator UI Enhanced. There you told me to join the OS Lead Platform and I joined after you said. Please add that PR also to my score.

okk .I think I have already reviewed that PR .

**Comment by apu52** [comment]
@Sanglap-Halder u are assigned with 30 points for this pR

**Pull request merged**
