### PR TITLE
Education Website

### LINKED ISSUE #516: Education Website
### Project title
education website

### Project Description
A website where users can explore multiple courses.

### Web stack

HTML , CSS AND JAVASCRIPT

### Screenshot(mandatory)
educationweb

#### Are you contributing under any open-source program ?
I am working under codepeak'23.

### PR DESCRIPTION
**Pull request by Mayank77maruti**
# Title and Issue number 

Title : Eduland

Issue No. : #516 

Code Stack : HTML , CSS AND JAVASCRIPT

Close #516 

# Video (mandatory)

Uploading EDUCATIONWEBVID.mp4…

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have updated the `projectData.json` file for my contribution
- [x] I have added the img of my project in the `assets/img` section

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***
I am working under codepeak'23.

### CODE REVIEW

**Comment by Mayank77maruti** [comment]
https://github.com/apu52/METAVERSE/assets/125661248/2fe12a8c-f2e4-425d-8150-fa84a1932a32

**Comment by Mayank77maruti** [comment]
Hey @shruti-sen2004 , Please do award bonus points for beautiful UI and functionality , which greatly enhances the project's quality.
Thank you for considering.

**Comment by apu52** [comment]
@Mayank77maruti The whole project is coped!!!!!!!!!
It is really very unprofessional behavior.

**Comment by apu52** [comment]
> Hey @shruti-sen2004 , Please do award bonus points for beautiful UI and functionality , which greatly enhances the project's quality. Thank you for considering.

No points will be awarded & further more Issues or PR like this will not be entertained.

**Pull request merged**
