### PR TITLE
Enchanced the UI for footer and about us section in Food Order Website.

### LINKED ISSUE #787: [UI Enhancement]: Enhance the UI for the food ordering website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently the menu is all cards lined up, by adding a hovering effect on the menu cards, it can increase the interactivity for the user.
The card can be made to pop out on hovered.

image

### Use Case

It would improve not only the interactivity for the user, but also increase the overall appeal of the UI of the website.

Please assign this issue to me, I would love to work on this!

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

### LINKED ISSUE #792: [UI Enhancement]: About Us Section and Footer of the Food Order Website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The footer of the food ordering website is not aligned properly, and the text extends to the borders of the footer. It can be made better by aligning the text properly, and making it match the rest of the website.
image

The text in the about us section is also not correctly justified, and looks misaligned with respect to other sections.
image

### Use Case

By improving the footer and about us section, it will increase the overall aesthetic and usability of the footer and make the entire page look more cohesive.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by meetalik8**
Title :[UI Enhancement]: About Us Section and Footer of the Food Order Website

Issue No. : #792 

Code Stack : HTML, CSS, Javascript

Close #792  

# Video (mandatory)

Changes Made:
About Us Section:
Before-
image

After-
image

Footer:
Before-
image
 
After-
image

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

### CODE REVIEW

**Comment by meetalik8** [comment]
@apu52 Hello, Could you please review this PR too? I would really appreciate it if you can assign it under gssoc. Thank you!

**Review by apu52 — CHANGES_REQUESTED** [review]
@meetalik8 The issue u have mentioned in this PR has already been closed .have u raised multiple PR regarding one single PR??
if yes, then I can't assign you points in GSSOC for this PR(as u have already been given point regarding the previous PR) as per the rules .Please try to make all of your changes in one single PR

**Comment by meetalik8** [comment]
Hello @apu52 I am so sorry, this was for another issue I added the wrong issue number. I changed it to the correct issue number #792 (https://github.com/apu52/METAVERSE/issues/792).

**Review by apu52 — APPROVED** [review]
@meetalik8 well done . good work

**Pull request merged**
