### PR TITLE
 The About us page of the Metaverse website is made readable in light mode.

### LINKED ISSUE #630: The About us page of Metaverse is not readable in light mode.
**Describe the bug**

The About page of the Metaverse website is not readable in light mode also it needs some corrections in CSS for proper alignment in mobile devices.
I can solve this issue.
Kindly assign me
Working under GSSOC 24

**Screenshots (Mandatory)**

Screenshot_20240514_095927_Chrome
Screenshot_20240514_095934_Chrome

### PR DESCRIPTION
**Pull request by Abhishek-465**
# Title and Issue number 

Title  The About us page of the Metaverse website is made readable in light mode.

Issue No. :#630 

Close #630

# Screenshots (mandatory)

Screenshot (51)

Screenshot (52)
Screenshot (53)

# Checklist:

-  [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

Yes under GSSOC

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@Abhishek-465 I think there is some problem As I can't see the theme change button in the About us page right now. in your deployment . Please make the necessary changes
image

**Comment by Abhishek-465** [comment]
Yes i see actually before my commits only the theme change button was not visible in some screen widths. Okay i am fixing it.

**Comment by Abhishek-465** [comment]
@apu52  Now the slider is visible in all devices. You can check it.

**Review by apu52 — APPROVED** [review]
@Abhishek-465 very good work

**Comment by Abhishek-465** [comment]
Thanks a lot @apu52

**Pull request merged**
