### PR TITLE
Google drive clone

### PR DESCRIPTION
**Pull request by paulsuryanshu**
# Google drive clone 30 

Title : Google drive clone

Issue No. : 30

Code Stack : HTML , CSS

Close #<issue_no>

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have updated the Index.html file for my contribution

### CODE REVIEW

**Comment by paulsuryanshu** [comment]
@apu52 merge it

**Comment by 5h0ov** [comment]
@paulsuryanshu looks good! thanks for contributing!

**Comment by 5h0ov** [comment]
but bro next time put ur projects in the Projects Folder!

**Comment by paulsuryanshu** [comment]
ok

**Pull request merged**
