### PR TITLE
Created QR ID CARD GENERATOR

### LINKED ISSUE #33: QR Id Card Generator
**Describe the project you want to add with tech stack**
I will code the project in HTML, CSS and, JS

**Expected behavior**
Users will be able to input their name and id and a ID card with updated QR will be generated

**Screenshots (optional)**

**Additional context (optional )**

@apu52 Please assign this issue to me.

### PR DESCRIPTION
**Pull request by ashish-bazad**
# Title and Issue number 

Title : Qr Id Card Generator

Issue No. : #33 

Code Stack : HTML, CSS, JavaScript

Close #<issue_no>
Close #33 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have updated the Index.html file for my contribution

### CODE REVIEW

**Comment by ashish-bazad** [comment]
@apu52 Please accept my Pull Request. 😊

**Review by apu52 — CHANGES_REQUESTED** [review]
@ashish-bazad Please try to add your project index.html.md file

**Comment by apu52** [comment]
@ashish-bazad the project is really fascinating & the idea is very unique. If possible please try to add some CSS styling in the background

**Comment by ashish-bazad** [comment]
> @ashish-bazad the project is really fascinating & the idea is very unique. If possible please try to add some CSS styling in the background

Sure Sir!

**Comment by ashish-bazad** [comment]
@apu52 now I have added the project in Index.html.md file and have formatted the project. Please accept.
Screenshot 2023-10-16 at 11 51 55 AM

**Comment by apu52** [comment]
@ashish-bazad Than you for your valuable contribution!!!
Make more contributions like this in this repo.

**Pull request merged**
