### PR TITLE
Added files and updated projectData.json

### LINKED ISSUE #268: Black Jack
### Project title
Black Jack

### Project Description
This is an engaging black jack game with card visual and scoreboard.

### Screenshot(mandatory)
image

#### Are you contributing under any open-source program ?
Codepeak 23
<hr/>

### PR DESCRIPTION
**Pull request by drockparashar**
# Title and Issue number 

Title : Black Jack

Issue No. :#268

Code Stack : HTML ,CSS, Javascript

Close #268 

# Video (mandatory)

https://github.com/apu52/METAVERSE/assets/118686637/9fe5379c-0631-40da-9ed2-03e3959b611e

# Checklist:

- [X ] I have mentioned the issue number in my Pull Request.
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have created a helpful and easy to understand `README.md`
- [X ] I have updated the `projectData.json` file for my contribution
- [ X] I have added the img of my project in the `assets/img` section

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***
Codepeak 23

### CODE REVIEW

**Review by 5h0ov — APPROVED** [review]

**Comment by 5h0ov** [comment]
@drockparashar  could you fix the conflict :)

**Comment by drockparashar** [comment]
Is is due to a previously added project?

**Comment by shruti-sen2004** [comment]
@5h0ov Merge conflict resolved...u can merge it now....

**Comment by 5h0ov** [comment]
> Is is due to a previously added project?

ye but it ok now

**Pull request merged**
