### PR TITLE
Project - Blog Website

### LINKED ISSUE #312: Add new project / Blogging Website
### Project title
The Blogging Website

### Project Description
This is the blogging website which gets in use to write a blogs. It is multipage blogging website.

### Web stack
HTML5 / CSS3 / JS

### Screenshot(mandatory)

p9

### Additional Context(mandatory)
This is specially made for practising html / css and multipage structure of websites.
#### Are you contributing under any open-source program ?

YES / Codepeak and KWoC
<hr/>

### PR DESCRIPTION
**Pull request by AaadityaG**
# Title and Issue number 

Title : Blog Website

Issue No. : #312

Code Stack :  HTML / CSS

Close #312

# Video (mandatory)

https://github.com/apu52/METAVERSE/assets/114663382/f29a6200-ce87-41af-ae2f-8217f6b77495

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have updated the `projectData.json` file for my contribution
- [x] I have added the img of my project in the `assets/img` section

**Additional context (Mandatory )**
Made for practising HTML / CSS
***Are you contributing under any Open-source programme?***

YES / Codepeak & KWoC

### CODE REVIEW

**Comment by apu52** [comment]
@AaadityaG Please resolve the merge conflicts

**Comment by AaadityaG** [comment]
I am not getting it.. Any Suggestion?

**Comment by apu52** [comment]
image

There is a conflict in the projectData.json file .You have to place your project at the last index of  that file.

**Comment by AaadityaG** [comment]
Raised new pr

**Pull request closed without merging**
