### PR TITLE
Ui of rate us page improved.✨

### PR DESCRIPTION
**Pull request by trahulprabhu38**
improved the Ui and added a storage feature which will store user data.
@apu52 can you review this please.

#1253 sovled.

Screenshot 2024-10-16 at 6 10 23 PM

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
i have one more PR to make , can you please review this .thank you!
@apu52

**Comment by T-Rahul-prabhu-38** [comment]
i have one more PR to make , can you please review this .thank you!
@apu52

**Comment by T-Rahul-prabhu-38** [comment]
@apu52 i have another PR to make , can you please review this .
thank you

**Comment by T-Rahul-prabhu-38** [comment]
@apu52 i have another PR to make , can you please review this .
thank you

**Comment by T-Rahul-prabhu-38** [comment]
@apu52 i have another PR to make , can you please review this .
thank you

**Comment by T-Rahul-prabhu-38** [comment]
[apu52](https://github.com/apu52) i have another PR to make , can you please review this .
thank you

**Comment by T-Rahul-prabhu-38** [comment]
[apu52](https://github.com/apu52) i have another PR to make , can you please review this .
thank you

**Comment by T-Rahul-prabhu-38** [comment]
[apu52](https://github.com/apu52) i have another PR to make , can you please review this .
thank you

**Review by apu52 — CHANGES_REQUESTED** [review]
@T-Rahul-prabhu-38 please try to fill the pr form correctly with all the details provided .otherwise i can't be bale to merge your pr & also try to add a prototype video like what are the changes u have made in the website
& also try to resolve the conflicts

**Pull request closed without merging**
