### PR TITLE
🐛 Fixes of Main page & Contributor page

### LINKED ISSUE #1248: [Feature Request]: make the contact us page better
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to see the contact page redesigned to improve user experience by organizing sections more clearly and using a more intuitive layout. Making the team member cards more readable, clearer input fields, and accessible fonts would enhance readability and ease of use. This change would make it easier for users to reach out and find necessary information quickly.

### Use Case

A user visiting the contact page should easily locate contact options, such as phone, email, or live chat, without confusion. This would reduce frustration when looking for support, ensuring a smoother interaction with the platform. It's particularly helpful for new visitors who may not be familiar with the interface.

### Benefits

This feature would improve user satisfaction, resulting in higher engagement and fewer support requests due to better clarity. It enhances accessibility, making it usable for a wider audience, including those with disabilities. Overall, it strengthens the platform's professionalism and usability for all visitors.

### Add ScreenShots

image
image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

### LINKED ISSUE #1284: [Bug]: No contributors page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no contributors section or page in the website. I searched the codebase but no PR or jsx file was included that resolves the contributors page

### Expected behavior

It should open a page that has information about all the contributors who have contributed to this project.

### Add ScreenShots/Videos

[METAVERSE-contributors.webm](https://github.com/user-attachments/assets/3d9d1bb2-c915-41fe-82a8-3e3ed46a3b85)

### On which device are you experiencing this bug?

Android, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a WOB'24(Winter Of Blockchain) contributor
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by yashksaini-coder**
# Title and Issue number 

Title : 🐛 Bug fixes of Main page & Contributor page

Issue No. : #1284 

Tech Stack : HTML, CSS, Javascript

Close #1284 

# Type of PR

- [X] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Add WEB3 project
- [ ] Other (specify): _______________

# Video (mandatory)
[METAVERSE-1248.webm](https://github.com/user-attachments/assets/3df2a81f-2db0-4339-9411-8c817443dda1)

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing
- [X] I have Starred the Repository.

# Checklist:(In case of Adding New WEB3 project only)

- [ ] I have made my Commits(of new project) under the  `Projects` folder
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] i have added the image of my project under `asstes/img` folder

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC'24 extended contributor
- [X] I'm a Winter of Blockchain(WOB'24) contributor
- [X] I'm a Hactoberfest'24 contributor  

---

Attached will show you that the bugs have been fixed & there are no merge conflicts any more. 

I found two bugs in the main page project Data not accessing, and the contributors page not properly. 
I have fixed both these bugs in this one PR. Can this PR be `level 3` @apu52 

Please review it, and assign it to me

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
@apu52 can you review this PR and add proper labels to it.

**Review by apu52 — CHANGES_REQUESTED** [review]
@yashksaini-coder the changes u have made are really great but this pr is facing some merge conflicts please try to resolve this so that I can review & merge this pr

**Comment by yashksaini-coder** [comment]
@apu52 check it now

**Review by apu52 — CHANGES_REQUESTED** [review]
image

here in the home page its showing that no projects are available 


image

& also the contributor page is not loading till now , I want to suggest u one thing please try to make a new branch in your forked repo & try to make all of your changes there by updating your branch & then push your changes & submit a new prt

**Comment by yashksaini-coder** [comment]
okh

**Pull request closed without merging**
