### PR TITLE
Add subscribe 

### LINKED ISSUE #1324: [Feature Request]: Subscribe to our newsletter
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add backend implementation for users to subscribing the newsletter of the website. 
Users filling their valid mail ids should receive a confirmation mail

### Use Case

Users will be notified for further updates and will keep them engaging to the platform.

### Benefits

Users will be notified for further updates and will keep them engaging to the platform.

### Add ScreenShots/Videos

Screenshot 2024-10-26 002725

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a WOB'24(Winter Of Blockchain) contributor
- [X] I'm a GSSOC'24 Extended contributor
- [X] I'm a Hacktoberfest'24  contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Title and Issue number 

Title : Subscribe to our newsletter

Issue No. : #1324 

Tech Stack : express node.js 

Close #1324 

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Add WEB3 project
- [ ] Other (specify): _______________

# Video (mandatory)
Screenshot 2024-10-27 203849
Screenshot 2024-10-27 204919

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing
- [X] I have Starred the Repository.

# Checklist:(In case of Adding New WEB3 project only)

- [ ] I have made my Commits(of new project) under the  `Projects` folder
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] i have added the image of my project under `asstes/img` folder

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC'24 extended contributor
- [ ] I'm a Winter of Blockchain(WOB'24) contributor
- [X] I'm a Hactoberfest'24 contributor

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@haseebzaki-07 

image

maybe the subscribe function is working locally on your machine try to make it global

**Comment by haseebzaki-07** [comment]
sure @apu52 I will do it.

**Comment by apu52** [comment]
@haseebzaki-07 yes i understand. As this is an open source so I am not sharing with u the backend URL here , no worries , i will do that farther , now i am merging your PR

**Comment by haseebzaki-07** [comment]
hey @apu52 could you please raise the level of the PR!

**Pull request merged**
