### PR TITLE
Temperature Converter UI Improved

### LINKED ISSUE #1027: [Feature Request]: Improve UI of Temperature Convertor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to improve the UI of the Temperature Converter

### Use Case

Improvement of UI will result in better user experiences

### Benefits

It will be more interactive for users

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Sanglap-Halder**
# Title and Issue number 

Title :Temperature Converter UI Improved

Issue No. :1027

Code Stack : 

Close #1027

# Video (mandatory)

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**
**Now:**
Temperature Converter

***Are you contributing under any Open-source programme?***

- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor

### CODE REVIEW

**Comment by Sanglap-Halder** [comment]
Please review this PR

**Review by apu52 — CHANGES_REQUESTED** [review]
@Sanglap-Halder there are some recent changes in the website . So the PR is facing some merge conflicts  .please try to resolve the issues so that I can review the PR & be able to merge it

**Comment by Sanglap-Halder** [comment]
Please check it if there are any more conflicts

**Comment by apu52** [comment]
@Sanglap-Halder 

image

here the other temperature parameters can't be seen until it's hovered. Please fix this problem

**Comment by Sanglap-Halder** [comment]
Please review once

**Review by apu52 — APPROVED** [review]

**Pull request merged**
