### PR TITLE
navbar_changed_hovereffect

### LINKED ISSUE #772: [Bug]: Hover effect on the navbar
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello @ap
The navigation bar appears visually unappealing and cluttered, which negatively impacts the overall design and user experience. 

### Expected behavior

The goal should be to create a visually appealing and functional navigation system that enhances the overall user experience, rather than detracting from it with an overwhelming or disjointed design.

### Add ScreenShots

Screenshot 2024-06-12 034114

Kindly assign this issue under GSSOC'24.
Thankyou

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sakshiglaze**
Hello @anuragverma108 

# Title and Issue number 

Title :Hover effect on the navbar 

Issue No. :#772

Code Stack : HTML, CSS, JS

Close #772

# Video (mandatory)
earlier---
Screenshot 2024-06-12 034114

now--
https://github.com/apu52/METAVERSE/assets/129287425/e9055126-d844-49c1-a525-281cbce83240

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC'24 contributor
- [x] I'm a SSOC'24 contributor

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
image

image


there are some unexpected bugs here. please try to resolve the unexpected errors

**Comment by sakshiglaze** [comment]
@apu52 
I'm sorry, I've accidently deleted the branch. Is there is way to reopen it? or I'll make another pull request.
Although, I've fixed the issue just trying to merge into the branch.
Sincere apologies.

**Comment by sakshiglaze** [comment]
Please be patient with me. I'm still learning how to use Git commits.

**Comment by apu52** [comment]
> @apu52 I'm sorry, I've accidently deleted the branch. Is there is way to reopen it? or I'll make another pull request. Although, I've fixed the issue just trying to merge into the branch. Sincere apologies.

no matter .it may happen I will suggest you to make a complete new branch & push all of your changes there

**Comment by sakshiglaze** [comment]
> > @apu52 I'm sorry, I've accidently deleted the branch. Is there is way to reopen it? or I'll make another pull request. Although, I've fixed the issue just trying to merge into the branch. Sincere apologies.
> 
> no matter No need to sorry .it may happen I will suggest you to make a complete new branch & push all of your changes there & make a complete new PR

Thankyou so much for consideration. new pr request is #838 
Also, I'll be highly obliged if you could add difficulty level LABEL to the issue #772

**Pull request closed without merging**
