### PR TITLE
Added dark theme to contact page

### LINKED ISSUE #709: Adding Light mode in contact us page
**Describe the bug**

Every page has light dark mode except contact us

**Expected behavior**

**Screenshots (Mandatory)**

image

**Additional context (Mandatory )**

***Are you contributing under any open-source program ?***

Yes I am contributing under gssoc24

### PR DESCRIPTION
**Pull request by agastya3636**
# Title and Issue number 

Title :Adding Light mode in contact us page 

Issue No. :#709

Code Stack : 

Close #709

# Video (mandatory)

image

image

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

Yes I am contributing under gssoc24

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
image

In light mode most of the texts are not visible Specially the img is looking like a negative picture , please recheck the fonts as well as the colors  in the light mode of the contact us page

**Comment by agastya3636** [comment]
@apu52  fixed please check it

image

**Comment by agastya3636** [comment]
@apu52 please check it

**Review by apu52 — APPROVED** [review]
@agastya3636 good work

**Pull request merged**
