### PR TITLE
Enhanced the UI of the contributors page

### LINKED ISSUE #1265: [Bug]: Enhancing the ui design of the contributors page.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Enhancing the ui design of the contributors page.

### Expected behavior

More good contributors page in place of just images and all i will make it super awersome and stylish according to the ui.

### Add ScreenShots

@apu52 Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

### On which device are you experiencing this bug?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by tarunkumar2005**
# Title and Issue number 

Title :Enhanced the UI of the contributors page

Issue No. : #1265 

Tech Stack : 

Close #1265

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Add WEB3 project
- [ ] Other (specify): _______________

# Video (mandatory)

https://github.com/user-attachments/assets/c86b864b-338b-4ba1-af3d-7b59ed26e18a

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing
- [x] I have Starred the Repository.

***Are you contributing under any Open-source programme?***

- [X] I'm a GSSOC'24 extended contributor
- [X] I'm a Hactoberfest'24 contributor  

@apu52 Please check this PR and merge it and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level. i think it can be level 3 because the page is very important in open source to showcase the efforts of the people contributing in building it and it is not static it is dynamic as a new contributor is added to your repo it will be automatically added there so this is the beauty of this.

I have put so much efforts to this ui design to please give it a level 3 else it is upto you i can only suggest.

### CODE REVIEW

**Comment by tarunkumar2005** [comment]
@apu52 When you get time check this PR.

**Review by apu52 — CHANGES_REQUESTED** [review]
@tarunkumar2005 I have reviewed the codes , the features u have added are working really great .
But The pr is facing some merge conflicts Please try to resolve it asap so that i can merge the pr

**Comment by tarunkumar2005** [comment]
@apu52 Done the changes you can check

**Review by apu52 — APPROVED** [review]
@tarunkumar2005 great work

**Pull request merged**
