### PR TITLE
Finance Tracker App

### PR DESCRIPTION
**Pull request by thanmaisai**
# Title and Issue number 

Title :Finance Tracker

Issue No. :  #63 

Code Stack : react,crypto-js,firebase,mantine

Close #67

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have updated the Index.html file for my contribution

**Additional context (Mandatory )**
 
- [x] I am a contributor in OSEN open source programme

 
- [x] I am a contributor in HACTOBERFEST 2023

### CODE REVIEW

**Comment by 5h0ov** [comment]
@thanmaisai  could you kindly rename the folder without any space like finance_tracker  becasue the deployment isnt working

**Review by apu52 — CHANGES_REQUESTED** [review]
Please rename The folder

**Review by apu52 — APPROVED** [review]
ok.lgtm

**Comment by thanmaisai** [comment]
> ok.lgtm

@apu52, could you please merge my pull request and include the appropriate labels for both Hacktoberfest and OSEN

**Comment by apu52** [comment]
@thanmaisai the deployment link is not working. Please try to check it.

**Review by apu52 — CHANGES_REQUESTED** [review]
please work on deployment problem

**Comment by thanmaisai** [comment]
> please work on deployment problem

@apu52 
I've thoroughly reviewed the README.md, GitHub Actions workflows, and repository settings, but unfortunately, I couldn't find specific deployment instructions. In my local environment, I used the following commands for deployment, and everything works as expected:

```
npm install -g serve
serve -s build
```

Could you kindly provide guidance on the intended deployment process for the project? Any insights or assistance you can offer would be immensely appreciated.

**Comment by apu52** [comment]
@thanmaisai Thank you for your valuable contribution!

**Pull request merged**
