### PR TITLE
Age Calculator UI Enhanced

### LINKED ISSUE #775: [Feature Request]: Improve the UI of Age Calculator
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Age Calculator has a very basic UI, it's just black and yellow color and white background. I want to improve it's UI under SSOC 2024

### Use Case

By improving  the UI it will look more attractive to the user

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Sanglap-Halder**
# Title and Issue number 

Title : Age Calculator UI Enhanced

Issue No. : 775

Code Stack : 

Close #775

# Video (mandatory)

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [ ] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
       

Age_Calc

### CODE REVIEW

**Review by apu52 — APPROVED** [review]
@Sanglap-Halder good changes

**Comment by apu52** [comment]
@Sanglap-Halder please join the OS lead platform (u can get the link from the official SSOC discord page) otherwise I can't assign u points

**Comment by Sanglap-Halder** [comment]
@apu52  I have joined the OS lead platform. Now you can assign me points

**Comment by apu52** [comment]
> @apu52 I have joined the OS lead platform. Now you can assign me points

As u have joined this Platform very late .Your leaderboard for this PR will not be updated. But don't worry at the end of the programme the points for this PR will be added with your final score

**Comment by Sanglap-Halder** [comment]
Thank you @apu52

**Pull request merged**
