### PR TITLE
logo is added in career crafters

### LINKED ISSUE #806: [Feature Request]: add a logo to the career crafters
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the main page of the career crafters logo is missing and also in the sidebar

### Use Case

By adding the logo it looks good 

### Benefits

_No response_

### Add ScreenShots

image
please assign me @pa

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by jayanththalla**
# Title and Issue number 

Title : add a logo to the career crafters

Issue No. : #806 

Code Stack :  HTML,css

Close #806 

# Video (mandatory)

https://github.com/apu52/METAVERSE/assets/121346142/c96e47ee-ce0e-4ee0-9d02-dee422addfd8

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor

### CODE REVIEW

**Review by apu52 — CHANGES_REQUESTED** [review]
@jayanththalla there is some merging conflicts in the PR , please try to check the conflicts & resolve it

**Review by apu52 — CHANGES_REQUESTED** [review]
image

The website is looking really messed up in your PR .Please review your changes .I think it is due to the **Merge branch to 'main'** commit .I would like to suggest you to make a complete new PR to avoid this type of conflicts

**Comment by jayanththalla** [comment]
> image
> 
> The website is looking really messed up in your PR .Please review your changes .I think it is due to the **Merge branch to 'main'** commit .I would like to suggest you to make a complete new PR to avoid this type of conflicts

sorry for that once check the pr again I made the commit's

**Review by apu52 — APPROVED** [review]
@jayanththalla good work

**Pull request merged**
